### ISSUE TITLE
Mock network tracking issues 

### ISSUE THREAD

**Issue by tuxcanfly** [rollkit/local-da#6]
### Implementation ideas

```[tasklist]
### Tasks
- [x] Create exhaustive list of celestia errors
- [ ] Move go-da dummy-da to mock-da
- [ ] Create mocks to replicate celestia errors
```
